
const ADMIN_ROLES = ["ADMIN", "ORG_OWNER"]
const STANDARD_ROLES = ["PRE_SALES", "ENGINEERING", "MARKETING" ]
const TEAM_LEADS = ["SALES_OWNER", "ACCOUNT_OWNER"]
const TEAM_MEMBERS = ["SALES_OWNER", "ACCOUNT_OWNER", "PRE_SALES", "ENGINEERING", "MARKETING" ]


const SALES_OWNER = "SALES_OWNER" 


module.exports = {ADMIN_ROLES, STANDARD_ROLES, TEAM_LEADS,TEAM_MEMBERS, SALES_OWNER }